### ISSUE TITLE
Build doesn't take care of resources

### ISSUE THREAD

**Issue by ron-b** [TheScienceOfCodeEDU/sdl-vscode-c-cpp#2]
Hey,

Tried to issue a PR but lacking permissions, anyways - I noticed that I can only "play" the game during debug, and that's due to the build folder not taking into account copying over the resource folder, here is a fix:

**build-win.bat** :
```bat
@echo off
mkdir "build/win" 2>NUL
xcopy /E /I "res" "build/win/res"
g++ main.cpp -IC:\sdl2\include\SDL2 -LC:\sdl2\lib -g -ggdb -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o build/win/main
```

**build-linux.sh** :
```bash
#!/bin/bash
mkdir -p build/linux
cp -r res build/linux/
g++ main.cpp -g -ggdb -w -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o build/linux/main
```

**build-mac.sh** :
```bash
#!/bin/bash
mkdir -p build/mac
cp -r res build/mac/
g++ main.cpp -g -ggdb -w -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o build/mac/main
```

**Comment by dacanizares** [comment]
Thanks [ron-b](https://github.com/ron-b)!

If you want, I can add you as a contributor so you'll get credit for those fixes. Otherwise, I can patch those files myself.

What do you think?

Best regards.

**Comment by ron-b** [comment]
Thanks, add me then, I might have some additional fixes later on👍🏻

**Comment by dacanizares** [comment]
Nice! I have sent you an invite.

**Comment by dacanizares** [comment]
Thanks Ron! I've tested on Linux and it worked perfectly. I've merged the PR.
